### ISSUE TITLE
Doesn't work with vue 3

### ISSUE THREAD

**Issue by SimonEdoki** [redsd/vue-apple-signin#2] opened 2022-10-18 20:29 UTC
**Bug**
vue-apple-signin.min.js?ec57:1 Uncaught (in promise) TypeError: createElement is not a function
    at Proxy.render (vue-apple-signin.min.js?ec57:1:1)
    at ...

**Comment by ebeton-ro** [comment] 2022-12-07 16:38
I can confirm this also

**Comment by redsd** [comment] 2023-01-08 17:48
sorry for the late response, I didnt seem to get any notification.

I will look into it.

**Comment by redsd** [comment] 2023-01-08 19:46
It should be fixed now

**Comment by eakenbor** [comment] 2023-01-08 21:12
@redsd how soon can the latest version appear on npmjs?

**Comment by redsd** [comment] 2023-01-09 11:22
@eakenbor it should be available now
`npm install vue-apple-login@2.x`

**Comment by eakenbor** [comment] 2023-01-09 13:00
@redsd thanks

**Comment by eakenbor** [comment] 2023-01-09 13:10
@redsd 
When trying to install it on my Vue 3, I received the following error:

````
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "3^.0.0": Tags may not have any characters that encodeURIComponent encodes.
````

I tried both npm install vue-apple-login@2.x and npm install vue-apple-login.

Please can you have a look at this?

**Comment by redsd** [comment] 2023-01-09 14:08
@eakenbor Check, should work now, package containend a typo which I overlooked....
Tested install now and it should work.

**Comment by eakenbor** [comment] 2023-01-09 15:48
@redsd Thanks. However, I could not get the Apple sign in component to display in the browser. I use Vuejs 3. 
 In the Elements, I saw this:

````
<div id="appleid-signin" data-mode="center-align" data-type="sign in" data-color="black" data-border="true" data-radius="15" data-width="100%" data-height="100%" data-logo-size="medium" data-logo-position="0" data-label-position="0" class="
                  border-color-grey
                  btn
                  input
                  padding-10
                  font-size-14
                  max-width-700
                  line-height-20
                  font-weight-400
                "></div>
````

Here is my code.

````
main.js

import VueAppleLogin from 'vue-apple-login';

app.use(VueAppleLogin, {
  clientId: 'com.test.web',
  scope: 'name email',
  redirectURI: 'https://test.com/login',
  state: new Date().toString(),
  usePopup: true,
});
````
````
Login.vue
  <div class="padding-top-18">
              <vue-apple-login
                mode="center-align"
                type="sign in"
                color="black"
                :border="true"
                :radius="15"
                width="100%"
                height="100%"
                logoSize="medium"
                :logoPosition="0"
                :labelPosition="0"
                className="
                  border-color-grey
                  btn
                  input
                  padding-10
                  font-size-14
                  max-width-700
                  line-height-20
                  font-weight-400
                "
                :onSuccess="onAppleSignInSuccess"
                :onFailure="
                  (error) => {
                    console.log(error);
                  }
                "
              ></vue-apple-login>
            </div>
````

Please see if you can help.

**Comment by redsd** [comment] 2023-01-09 16:16
@eakenbor did you include `<script type="text/javascript" src="https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js"></script> `?
Otherwise templates could interfere with Apple styling that is added in the div

**Comment by eakenbor** [comment] 2023-01-09 19:13
@redsd thanks. It appears now. However, is there anyway I can use my own custom button and logo?

**Comment by EricVanEldik** [comment] 2023-01-10 05:44
@eakenbor You can't change the button it self, because this is generated by Apple's js library.
What you could do is create your own button, hide the apple one and trigger a click on the apple button when your own custom button is pressed.

**Comment by eakenbor** [comment] 2023-01-10 14:49
@redsd but it does not say in the documentation how to hide the apple button, or does it? Please how can I do that and where do I insert my custom button? Thanks.

**Comment by redsd** [comment] 2023-01-10 19:20
@eakenbor yes, because it goes against Apple's guidelines and I would not recommend it.

Hiding a button and triggering a click are basic css and JS skills, I would recommend Google for this.

Since the issue is fixed I while close this thread.

**Closed as completed by redsd** 2023-01-10 19:20 UTC
